<?php echo $this->doctype('HTML5') ?>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <?php echo $this->headTitle() ?>
  
  <meta name="description" content="">
  <meta name="author" content="">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <link rel="stylesheet" href="/css/style.css?v=2">
  <link rel="stylesheet" href="/css/960.css?v=2">
  <script src="/js/libs/modernizr-1.7.min.js"></script>

</head>
<?php
$fc = Zend_Controller_Front::getInstance()->getRequest();
?>
<body class="<?php echo $fc->getControllerName() . '-' . $fc->getActionName(); ?>">


    <header>
        <?php echo $this->render('_header.phtml') ?>
    </header>
    <nav>
        <?php echo $this->render('_nav.phtml') ?>
    </nav>
    
    
  <div id="container" class="container_12 clearfix">
    
      
    <div id="main" role="main" class="grid_10 alpha">
        <div><?php echo $this->flashMessenger(); ?></div>
        <?php echo $this->layout()->content ?>
    </div>
      
  </div> <!-- / #container -->
        <footer>
    <?php echo $this->render('_footer.phtml') ?>
      </footer>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js"></script>
  <script>window.jQuery || document.write("<script src='/js/libs/jquery-1.5.1.min.js'>\x3C/script>")</script>
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js"></script>

  <!-- scripts concatenated and minified via ant build script-->
  <script src="/js/plugins.js"></script>
  <script src="/js/script.js"></script>
  <!-- end scripts-->


  <!--[if lt IE 7 ]>
    <script src="/js/libs/dd_belatedpng.js"></script>
    <script>DD_belatedPNG.fix("img, .png_bg");</script>
  <![endif]-->



  <script>
    var _gaq=[["_setAccount","UA-XXXXX-X"],["_trackPageview"]]; // Change UA-XXXXX-X to be your site's ID
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));
  </script>

<?php echo $this->headScript(); ?>
</body>
</html>